### ISSUE TITLE
ccaa_covid19_fallecidos.csv update

### ISSUE THREAD

**Issue by fgallardo** [datadista/datasets#105]
Hi,

First of all, thanks for putting up this information repository, it has been of great help during the last few weeks to monitor the status of the COVID in Spain.

I wanted to ask you, as I noticed there is no new data since the one from 2020-05-24. Are you planning to still update the csv on a daily basis?

Again, thanks a  lot for your effort.

Best regards

**Comment by adelgadob** [comment]
We are updating only the national dataset and not the data by autonomous community due to a change in the data collection methodology by the Ministry of Health. The previous series is not
comparable with the current one and the Carlos III Health Institute, the body in charge of publishing the historical series, has paralyzed the publication of data until they can correct it.

**Comment by fgallardo** [comment]
Thanks a lot! :+1:
